services:
  jupyter:
    container_name: jupyter
    build: .
    working_dir: /home/
    ports:
      - "8888:8888"
    command: jupyter lab --allow-root --ip 0.0.0.0 --port 8888 --NotebookApp.password='' 
    volumes:
      - ./:/home/
      - ./index.css:/usr/local/share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css